import { ContentItem } from '../types/content';

export const INITIAL_SAMPLE_CONTENT: ContentItem[] = [
  {
    id: 'ch-101',
    title: '10 Game-Changing VS Code Shortcuts Every Dev Should Know',
    description: 'A snappy 45-second walkthrough demonstrating multi-cursor, bracket matching, and zen mode shortcuts with overlay visual cues.',
    platform: 'Instagram',
    contentType: 'Reel',
    status: 'Published',
    scheduledDate: '2026-09-28',
    notes: 'Pinned comment with link to cheatsheet PDF. Great audience retention on the multi-cursor tip.',
    createdAt: '2026-09-25T10:15:00.000Z',
    updatedAt: '2026-09-28T14:30:00.000Z',
  },
  {
    id: 'ch-102',
    title: 'Building an Autonomous AI Agent in 15 Minutes (Step-by-Step)',
    description: 'Full-length tutorial covering project scaffolding, tool calling loops, LLM prompt formatting, and testing in Antigravity IDE.',
    platform: 'YouTube',
    contentType: 'Short',
    status: 'Scheduled',
    scheduledDate: '2026-10-08',
    notes: 'Thumbnail ready: High-contrast title card with split IDE screenshot. Add code repository link in description.',
    createdAt: '2026-10-01T08:45:00.000Z',
    updatedAt: '2026-10-03T16:20:00.000Z',
  },
  {
    id: 'ch-103',
    title: 'When the bug only reproduces on production on Friday 5 PM',
    description: 'Relatable relatable developer meme using the classic dramatic reaction gif format.',
    platform: 'X',
    contentType: 'Meme',
    status: 'Published',
    scheduledDate: '2026-10-02',
    notes: 'High organic reshares. Tag #devhumor and #codingcommunity.',
    createdAt: '2026-10-02T16:00:00.000Z',
    updatedAt: '2026-10-02T17:05:00.000Z',
  },
  {
    id: 'ch-104',
    title: 'The Modern Frontend Architecture Matrix in 2026',
    description: 'Carousel infographic comparing SSR, SSG, Islands Architecture, and Client Hydration trade-offs.',
    platform: 'Facebook',
    contentType: 'Image',
    status: 'Draft',
    scheduledDate: '2026-10-12',
    notes: 'Slide 4 needs chart simplification before publishing. Double check benchmark citations.',
    createdAt: '2026-10-03T11:20:00.000Z',
    updatedAt: '2026-10-04T09:10:00.000Z',
  },
  {
    id: 'ch-105',
    title: 'Why I stopped using bloated UI libraries and built my own tokens',
    description: 'Deep-dive text thread on design tokens, CSS variables, bundle sizes, and maintenance overhead.',
    platform: 'X',
    contentType: 'Text',
    status: 'Idea',
    scheduledDate: '',
    notes: 'Draft the 7-part thread in markdown first. Include metrics on bundle size reduction.',
    createdAt: '2026-10-04T14:30:00.000Z',
    updatedAt: '2026-10-04T14:30:00.000Z',
  },
  {
    id: 'ch-106',
    title: 'Satisfying CSS animations that take less than 10 lines',
    description: 'Smooth glowing border effect and springy hover states demonstrated with live code side-by-side.',
    platform: 'TikTok',
    contentType: 'Reel',
    status: 'Scheduled',
    scheduledDate: '2026-10-07',
    notes: 'Use trending lofi audio track. Add subtitle captions for sound-off viewers.',
    createdAt: '2026-10-04T18:00:00.000Z',
    updatedAt: '2026-10-05T08:15:00.000Z',
  },
  {
    id: 'ch-107',
    title: 'Deep Dive: State Management in 2026 - Signals vs Reducers',
    description: 'Comprehensive comparison video with interactive sandboxes, memory profiling, and re-render benchmarks.',
    platform: 'YouTube',
    contentType: 'Short',
    status: 'Draft',
    scheduledDate: '2026-10-15',
    notes: 'Record voiceover for chapter 3. Intro hook animation is completed.',
    createdAt: '2026-10-05T09:00:00.000Z',
    updatedAt: '2026-10-05T11:30:00.000Z',
  },
  {
    id: 'ch-108',
    title: '5 Git commands that saved my career after an accidental force-push',
    description: 'Explaining git reflog, cherry-pick recovery, worktrees, and detached head rescue in simple diagrams.',
    platform: 'Instagram',
    contentType: 'Image',
    status: 'Published',
    scheduledDate: '2026-09-30',
    notes: 'Save as permanent story highlight under "Dev Cheats".',
    createdAt: '2026-09-29T13:40:00.000Z',
    updatedAt: '2026-09-30T10:00:00.000Z',
  },
  {
    id: 'ch-109',
    title: 'Is Tailwind v4 the end of separate CSS files?',
    description: 'Quick poll and commentary on zero-config engine and lightningcss integration.',
    platform: 'TikTok',
    contentType: 'Short',
    status: 'Idea',
    scheduledDate: '',
    notes: 'Gather developer sentiment quotes from Discord & GitHub discussions.',
    createdAt: '2026-10-05T12:00:00.000Z',
    updatedAt: '2026-10-05T12:00:00.000Z',
  }
];
